In [3]:
import numpy as np

In [ ]:
## Array Creation

In [4]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [8]:
type(a)

numpy.ndarray

In [7]:
a.ndim

1

In [ ]:
## Zero dimentional array

In [10]:
z = np.array(10)
z

array(10)

In [11]:
z.ndim

0

In [17]:
  ## One dimentional array
  s = np.array([1,2,3]) 
  s

array([1, 2, 3])

In [18]:
s.ndim

1

In [15]:
  ## Two dimentional array
  t = np.array([[1,2,3]]) 
  t


array([[1, 2, 3]])

In [16]:
t.ndim

2

In [21]:
  ## Three dimentional array
  u = np.array([[[1,2,3]]]) 
  u

array([[[1, 2, 3]]])

In [22]:
u.ndim

3

In [23]:
## Change the data type of the array elements

In [26]:
x = np.array([[1,2,3,4,5]],dtype='float')
x

array([[1., 2., 3., 4., 5.]])

In [27]:
Y = np.array([[1,2,3,4,5]],dtype='str')
Y

array([['1', '2', '3', '4', '5']], dtype='<U1')

# **Other Ways of creating array**
*   Arange

*   Linspace
*   Zeros


*   Ones








In [29]:
a = np.arange(10,21)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [30]:
b = np.arange(100,201)
b

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199, 200])

In [37]:
c = np.linspace(1,10,20)
c

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [39]:
## retspet will give the intreval that the values are distributed in
d = np.linspace(1,10,20, retstep=True)
d

(array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
         3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
         5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
         8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ]),
 0.47368421052631576)

In [40]:
e = np.zeros([2,2])
e

array([[0., 0.],
       [0., 0.]])

In [41]:
f = np.ones([2,2])
f

array([[1., 1.],
       [1., 1.]])

# **Slicing and Indexing**

In [43]:
G = np.array([[1,2,3],[7,8,9]])
G

array([[1, 2, 3],
       [7, 8, 9]])

In [54]:
## to slice we give rows first, then column, Viz G [Rows, Cols]

G[0,0]

1

In [47]:
G[0,1:]

array([2, 3])

In [48]:
G[:,1:]

array([[2, 3],
       [8, 9]])

In [49]:
G[1:,:]

array([[7, 8, 9]])

In [50]:
G[1:,1:]

array([[8, 9]])

In [53]:
G[1:,2]

array([9])

In [56]:
G[:,0:1]

array([[1],
       [7]])

In [57]:
G[:,0:2]

array([[1, 2],
       [7, 8]])

In [62]:
G[[0,0],[1,2]]

array([2, 3])

In [63]:
G[[0,1],[1,2]]

array([2, 9])

In [61]:
G[[0,0,1,1],[1,2,0,1]]

array([2, 3, 7, 8])

# **Aggregate Functions**

In [66]:
F = np.array([1,2,3,4,5])


In [67]:
F.sum()

15

In [68]:
F.min()

1

In [70]:
F.max()

5

In [73]:
F.mean()

3.0

In [72]:
F.std()

1.4142135623730951

# **Stacking**

In [75]:
a = np.array([1,2,3])
b = np.array ([4,5,6])

In [77]:
c = np.vstack([a,b])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
d = np.hstack([a,b])
d

array([1, 2, 3, 4, 5, 6])